#lang racket
(provide (all-defined-out))
(require "pa1.rkt")

;; ============================================================
;; CSCE 322 - PA2 Starter File
;;
;; In this assignment you will:
;;   1. evaluate prefix expressions generated by your PA1 code
;;   2. implement runtime type checking
;;   3. handle and propagate runtime errors
;;
;; Allowed style:
;;   - top-level define only
;;   - recursion
;;   - if / cond
;;   - basic list operations
;;
;; Not allowed:
;;   - let / let*
;;   - lambda
;;   - nested define
;;   - mutation
;;   - loops
;; ============================================================

;; ============================================================
;; Name: TODO
;; ============================================================


;; ============================================================
;; Error helpers
;; ============================================================

(define (type-error? x)
  (equal? x '(err "type error")))

(define (div-zero-error? x)
  (equal? x '(err "division by zero")))

(define (any-error? x)
  (and (list? x)
       (not (null? x))
       (equal? (car x) 'err)))


;; ============================================================
;; evaluate-prefix
;;
;; Input:
;;   a valid prefix AST (generated by infix->prefix)
;;
;; Output:
;;   the evaluated value (number or boolean)
;;   OR a runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-prefix ast)
  (cond
    ;; Base cases: literals
    [(number? ast) ast]
    [(equal? ast 'true) 'true]
    [(equal? ast 'false) 'false]

    ;; TODO: handle unary operators
    ;; TODO: handle binary operators
    ;; TODO: implement type checking
    ;; TODO: implement division by zero check
    ;; TODO: propagate errors from subexpressions

    [else
     ;; Placeholder
     ast]))


;; ============================================================
;; evaluate-program
;;
;; Input:
;;   any Racket value (infix expression)
;;
;; Output:
;;   the evaluated value
;;   OR a PA1 syntax error
;;   OR a PA2 runtime error
;;
;; TODO:
;;   implement this function
;; ============================================================

(define (evaluate-program e)
  (cond
    ;; 1. Call your PA1 infix->prefix
    ;; 2. If it returns an error, return that error
    ;; 3. If it returns a valid AST, pass it to evaluate-prefix
    [else
     ;; Placeholder
     e]))


;; ============================================================
;; Public test cases
;;
;; You may add more tests as you work.
;; ============================================================

;; (evaluate-program 5)
;; (evaluate-program '(1 + 2))
;; (evaluate-program '(1 + 2 * 3))
;; (evaluate-program '(1 + * 3))
;; (evaluate-program '(1 + true))
;; (evaluate-program '(1 / (2 - 2)))
